Updated the bash scripts to be cleaner, and to change to the correct directory upon execution

diff --git a/bin/compile_thesis b/bin/compile_thesis
--- a/bin/compile_thesis
+++ b/bin/compile_thesis
@@ -1,17 +1,21 @@
 #!/bin/bash
 
+cd $(dirname $0)/..  # change to the correct directory
+
 THESIS="thesis.tex"
 
-if [[ ! -e $THESIS ]]; then
-    echo "Please execute this command in the base thesis directory"
+if [[ ! -e $THESIS ]]
+then
+    >&2 echo "Please execute this command in the base thesis directory"
     exit 1
 fi
 
 
-if which latexmk > /dev/null; then
+if which latexmk > /dev/null
+then
     LATEXMK=`which latexmk`
 else
-    echo "latexmk could not be found"
+    >&2 echo "latexmk could not be found"
     exit 1
 fi
 
